version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-server
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=rickandmorty
    ports:
      - "5432:5432"
