/* Data for locations */
INSERT INTO location VALUES (1, "Earth (C-137)", "Planet", "Dimension C-137");
INSERT INTO location VALUES (2, "Abadango", "Cluster", "unknown");
INSERT INTO location VALUES (3, "Citadel of Ricks", "Space station", "unknown");
INSERT INTO location VALUES (4, "Worldender's lair", "Planet", "unknown");
INSERT INTO location VALUES (5, "Anatomy Park", "Microverse", "Dimension C-137");
INSERT INTO location VALUES (6, "Interdimensional Cable", "TV", "unknown");
INSERT INTO location VALUES (7, "Immortality Field Resort", "Resort", "unknown");
INSERT INTO location VALUES (8, "Post-Apocalyptic Earth", "Planet", "Post-Apocalyptic Dimension");
INSERT INTO location VALUES (9, "Purge Planet", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (10, "Venzenulon 7", "Planet", "unknown");
INSERT INTO location VALUES (11, "Bepis 9", "Planet", "unknown");
INSERT INTO location VALUES (12, "Cronenberg Earth", "Planet", "Cronenberg Dimension");
INSERT INTO location VALUES (13, "Nuptia 4", "Planet", "unknown");
INSERT INTO location VALUES (14, "Giant's Town", "Fantasy town", "Fantasy Dimension");
INSERT INTO location VALUES (15, "Bird World", "Planet", "unknown");
INSERT INTO location VALUES (16, "St. Gloopy Noops Hospital", "Space station", "unknown");
INSERT INTO location VALUES (17, "Earth (5-126)", "Planet", "Dimension 5-126");
INSERT INTO location VALUES (18, "Mr. Goldenfold's dream", "Dream", "Dimension C-137");
INSERT INTO location VALUES (19, "Gromflom Prime", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (20, "Earth (Replacement Dimension)", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (21, "Testicle Monster Dimension", "Dimension", "Testicle Monster Dimension");
INSERT INTO location VALUES (22, "Signus 5 Expanse", "unknown", "Cromulon Dimension");
INSERT INTO location VALUES (23, "Earth (C-500A)", "Planet", "Dimension C-500A");
INSERT INTO location VALUES (24, "Rick's Battery Microverse", "Microverse", "Replacement Dimension");
INSERT INTO location VALUES (25, "The Menagerie", "Menagerie", "unknown");
INSERT INTO location VALUES (26, "Earth (K-83)", "Planet", "Dimension K-83");
INSERT INTO location VALUES (27, "Hideout Planet", "Planet", "unknown");
INSERT INTO location VALUES (28, "Unity's Planet", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (29, "Dorian 5", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (30, "Earth (Unknown dimension)", "Planet", "unknown");
INSERT INTO location VALUES (31, "Earth (J19ζ7)", "Planet", "Dimension J19ζ7");
INSERT INTO location VALUES (32, "Roy: A Life Well Lived", "Game", "Replacement Dimension");
INSERT INTO location VALUES (33, "Eric Stoltz Mask Earth", "Planet", "Eric Stoltz Mask Dimension");
INSERT INTO location VALUES (34, "Earth (Evil Rick's Target Dimension)", "Planet", "Evil Rick's Target Dimension");
INSERT INTO location VALUES (35, "Planet Squanch", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (36, "Glaagablaaga", "Planet", "unknown");
INSERT INTO location VALUES (37, "Resort Planet", "Planet", "unknown");
INSERT INTO location VALUES (38, "Interdimensional Customs", "Customs", "unknown");
INSERT INTO location VALUES (39, "Galactic Federation Prison", "Space station", "unknown");
INSERT INTO location VALUES (40, "Gazorpazorp", "Planet", "unknown");
INSERT INTO location VALUES (41, "Hamster in Butt World", "Planet", "unknown");
INSERT INTO location VALUES (42, "Earth (Giant Telepathic Spiders Dimension)", "Planet", "Giant Telepathic Spiders Dimension");
INSERT INTO location VALUES (43, "Alphabetrium", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (44, "Jerryboree", "Daycare", "unknown");
INSERT INTO location VALUES (45, "Krootabulon", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (46, "Zigerion's Base", "Space station", "Dimension C-137");
INSERT INTO location VALUES (47, "Pluto", "Dwarf planet (Celestial Dwarf)", "Replacement Dimension");
INSERT INTO location VALUES (48, "Fantasy World", "Planet", "Fantasy Dimension");
INSERT INTO location VALUES (49, "Zeep Xanflorp's Miniverse", "Miniverse", "Replacement Dimension");
INSERT INTO location VALUES (50, "Kyle's Teenyverse", "Teenyverse", "Replacement Dimension");
INSERT INTO location VALUES (51, "Larva Alien's Planet", "Planet", "Unknown dimension");
INSERT INTO location VALUES (52, "Earth (K-22)", "Planet", "Dimension K-22");
INSERT INTO location VALUES (53, "Mr. Meeseeks Box", "Box", "unknown");
INSERT INTO location VALUES (54, "Vindicator's Base", "Spacecraft", "unknown");
INSERT INTO location VALUES (55, "Pawn Shop Planet", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (56, "Mega Gargantuan Kingdom", "Microverse", "Replacement Dimension");
INSERT INTO location VALUES (57, "Gear World", "Planet", "unknown");
INSERT INTO location VALUES (58, "Earth (D-99)", "Planet", "Dimension D-99");
INSERT INTO location VALUES (59, "Earth (D716)", "Planet", "Dimension D716");
INSERT INTO location VALUES (60, "Earth (D716-B)", "Planet", "Dimension D716-B");
INSERT INTO location VALUES (61, "Earth (D716-C)", "Planet", "Dimension D716-C");
INSERT INTO location VALUES (62, "Earth (J-22)", "Planet", "Dimension J-22");
INSERT INTO location VALUES (63, "Froopyland", "Artificially generated world", "Replacement Dimension");
INSERT INTO location VALUES (64, "Detoxifier", "Machine", "Replacement Dimension");
INSERT INTO location VALUES (65, "Trunk World", "Planet", "unknown");
INSERT INTO location VALUES (66, "Plopstar", "Planet", "unknown");
INSERT INTO location VALUES (67, "Blips and Chitz", "Arcade", "Replacement Dimension");
INSERT INTO location VALUES (68, "Girvonesk", "unknown", "unknown");
INSERT INTO location VALUES (69, "Earth (C-35)", "Planet", "Dimension C-35");
INSERT INTO location VALUES (70, "Snuffles' Dream", "Dream", "Dimension C-137");
INSERT INTO location VALUES (71, "Earth (Pizza Dimension)", "Planet", "Pizza Dimension");
INSERT INTO location VALUES (72, "Earth (Phone Dimension)", "Planet", "Phone Dimension");
INSERT INTO location VALUES (73, "Greasy Grandma World", "Planet", "unknown");
INSERT INTO location VALUES (74, "Earth (Chair Dimension)", "Planet", "Chair Dimension");
INSERT INTO location VALUES (75, "Árboles Mentirosos", "Planet", "unknown");
INSERT INTO location VALUES (76, "Alien Day Spa", "Spa", "unknown");
INSERT INTO location VALUES (77, "Earth (Fascist Dimension)", "Planet", "Fascist Dimension");
INSERT INTO location VALUES (78, "Snake Planet", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (79, "Forbodulon Prime", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (80, "Earth (Fascist Shrimp Dimension)", "Planet", "Fascist Shrimp Dimension");
INSERT INTO location VALUES (81, "Earth (Fascist Teddy Bear Dimension)", "Planet", "Fascist Teddy Bear Dimension");
INSERT INTO location VALUES (82, "Earth (Wasp Dimension)", "Planet", "Wasp Dimension");
INSERT INTO location VALUES (83, "Monogatron Mothership", "Space station", "Replacement Dimension");
INSERT INTO location VALUES (84, "Gorgon Quadrant", "Quadrant", "Replacement Dimension");
INSERT INTO location VALUES (85, "Midland Quasar", "Quasar", "Replacement Dimension");
INSERT INTO location VALUES (86, "Mount Space Everest", "Mount", "Replacement Dimension");
INSERT INTO location VALUES (87, "Globaflyn", "Liquid", "Replacement Dimension");
INSERT INTO location VALUES (88, "Heist-Con", "Convention", "Replacement Dimension");
INSERT INTO location VALUES (89, "Heistotron Base", "Space station", "Replacement Dimension");
INSERT INTO location VALUES (90, "Mount Olympus", "Mount", "Replacement Dimension");
INSERT INTO location VALUES (91, "Plitzville Montana", "Woods", "Replacement Dimension");
INSERT INTO location VALUES (92, "Earth (Tusk Dimension)", "Planet", "Tusk Dimension");
INSERT INTO location VALUES (93, "Gramuflack", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (94, "Draygon", "Planet", "Magic Dimension");
INSERT INTO location VALUES (95, "New Improved Galactic Federation Quarters", "Space station", "Replacement Dimension");
INSERT INTO location VALUES (96, "Story Train", "Diegesis", "Replacement Dimension");
INSERT INTO location VALUES (97, "Non-Diegetic Alternative Reality", "Non-Diegetic Alternative Reality", "Replacement Dimension");
INSERT INTO location VALUES (98, "Tickets Please Guy Nightmare", "Nightmare", "Replacement Dimension");
INSERT INTO location VALUES (99, "Morty’s Story", "Diegesis", "Replacement Dimension");
INSERT INTO location VALUES (100, "Ricks’s Story", "Diegesis", "Replacement Dimension");
INSERT INTO location VALUES (101, "Glorzo Asteroid", "Asteroid", "Replacement Dimension");
INSERT INTO location VALUES (102, "Alien Acid Plant", "Acid Plant", "Replacement Dimension");
INSERT INTO location VALUES (103, "Merged Universe", "Dimension", "Merged Dimension");
INSERT INTO location VALUES (104, "Near-Duplicate Reality", "Reality", "Unknown dimension");
INSERT INTO location VALUES (105, "NX-5 Planet Remover", "Death Star", "Replacement Dimension");
INSERT INTO location VALUES (106, "Gaia", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (107, "Defiance's Ship", "Spacecraft", "Replacement Dimension");
INSERT INTO location VALUES (108, "Defiance's Base", "Base", "Replacement Dimension");
INSERT INTO location VALUES (109, "The Ocean", "Liquid", "Replacement Dimension");
INSERT INTO location VALUES (110, "Narnia Dimension", "Dimension", "Fantasy Dimension");
INSERT INTO location VALUES (111, "Elemental Rings", "Elemental Rings", "Replacement Dimension");
INSERT INTO location VALUES (112, "Morglutz", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (113, "Ferkus 9", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (114, "Morty", "Human", "Replacement Dimension");
INSERT INTO location VALUES (115, "Space", "Space", "Replacement Dimension");
INSERT INTO location VALUES (116, "Hell", "Hell", "Replacement Dimension");
INSERT INTO location VALUES (117, "Z. Q. P. D.", "Police Department", "Replacement Dimension");
INSERT INTO location VALUES (118, "Space Tahoe", "", "Replacement Dimension");
INSERT INTO location VALUES (119, "France", "Country", "Replacement Dimension");
INSERT INTO location VALUES (120, "Birdperson's Consciousness", "Consciousness", "Replacement Dimension");
INSERT INTO location VALUES (121, "Rick's Consciousness", "Consciousness", "Replacement Dimension");
INSERT INTO location VALUES (122, "Avian Planet", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (123, "Normal Size Bug Dimension", "Dimension", "");
INSERT INTO location VALUES (124, "Slartivart", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (125, "Rick and Two Crows Planet", "Planet", "Replacement Dimension");
INSERT INTO location VALUES (126, "Rick's Memories", "Memory", "");

/* Data for episodes */
INSERT INTO episode VALUES (1, "Pilot", "December 2, 2013", "S01E01");
INSERT INTO episode VALUES (2, "Lawnmower Dog", "December 9, 2013", "S01E02");
INSERT INTO episode VALUES (3, "Anatomy Park", "December 16, 2013", "S01E03");
INSERT INTO episode VALUES (4, "M. Night Shaym-Aliens!", "January 13, 2014", "S01E04");
INSERT INTO episode VALUES (5, "Meeseeks and Destroy", "January 20, 2014", "S01E05");
INSERT INTO episode VALUES (6, "Rick Potion #9", "January 27, 2014", "S01E06");
INSERT INTO episode VALUES (7, "Raising Gazorpazorp", "March 10, 2014", "S01E07");
INSERT INTO episode VALUES (8, "Rixty Minutes", "March 17, 2014", "S01E08");
INSERT INTO episode VALUES (9, "Something Ricked This Way Comes", "March 24, 2014", "S01E09");
INSERT INTO episode VALUES (10, "Close Rick-counters of the Rick Kind", "April 7, 2014", "S01E10");
INSERT INTO episode VALUES (11, "Ricksy Business", "April 14, 2014", "S01E11");
INSERT INTO episode VALUES (12, "A Rickle in Time", "July 26, 2015", "S02E01");
INSERT INTO episode VALUES (13, "Mortynight Run", "August 2, 2015", "S02E02");
INSERT INTO episode VALUES (14, "Auto Erotic Assimilation", "August 9, 2015", "S02E03");
INSERT INTO episode VALUES (15, "Total Rickall", "August 16, 2015", "S02E04");
INSERT INTO episode VALUES (16, "Get Schwifty", "August 23, 2015", "S02E05");
INSERT INTO episode VALUES (17, "The Ricks Must Be Crazy", "August 30, 2015", "S02E06");
INSERT INTO episode VALUES (18, "Big Trouble in Little Sanchez", "September 13, 2015", "S02E07");
INSERT INTO episode VALUES (19, "Interdimensional Cable 2: Tempting Fate", "September 20, 2015", "S02E08");
INSERT INTO episode VALUES (20, "Look Who's Purging Now", "September 27, 2015", "S02E09");
INSERT INTO episode VALUES (21, "The Wedding Squanchers", "October 4, 2015", "S02E10");
INSERT INTO episode VALUES (22, "The Rickshank Rickdemption", "April 1, 2017", "S03E01");
INSERT INTO episode VALUES (23, "Rickmancing the Stone", "July 30, 2017", "S03E02");
INSERT INTO episode VALUES (24, "Pickle Rick", "August 6, 2017", "S03E03");
INSERT INTO episode VALUES (25, "Vindicators 3: The Return of Worldender", "August 13, 2017", "S03E04");
INSERT INTO episode VALUES (26, "The Whirly Dirly Conspiracy", "August 20, 2017", "S03E05");
INSERT INTO episode VALUES (27, "Rest and Ricklaxation", "August 27, 2017", "S03E06");
INSERT INTO episode VALUES (28, "The Ricklantis Mixup", "September 10, 2017", "S03E07");
INSERT INTO episode VALUES (29, "Morty's Mind Blowers", "September 17, 2017", "S03E08");
INSERT INTO episode VALUES (30, "The ABC's of Beth", "September 24, 2017", "S03E09");
INSERT INTO episode VALUES (31, "The Rickchurian Mortydate", "October 1, 2017", "S03E10");
INSERT INTO episode VALUES (32, "Edge of Tomorty: Rick, Die, Rickpeat", "November 10, 2019", "S04E01");
INSERT INTO episode VALUES (33, "The Old Man and the Seat", "November 17, 2019", "S04E02");
INSERT INTO episode VALUES (34, "One Crew Over the Crewcoo's Morty", "November 24, 2019", "S04E03");
INSERT INTO episode VALUES (35, "Claw and Hoarder: Special Ricktim's Morty", "December 8, 2019", "S04E04");
INSERT INTO episode VALUES (36, "Rattlestar Ricklactica", "December 15, 2019", "S04E05");
INSERT INTO episode VALUES (37, "Never Ricking Morty", "May 3, 2020", "S04E06");
INSERT INTO episode VALUES (38, "Promortyus", "May 10, 2020", "S04E07");
INSERT INTO episode VALUES (39, "The Vat of Acid Episode", "May 17, 2020", "S04E08");
INSERT INTO episode VALUES (40, "Childrick of Mort", "May 24, 2020", "S04E09");
INSERT INTO episode VALUES (41, "Star Mort: Rickturn of the Jerri", "May 31, 2020", "S04E10");
INSERT INTO episode VALUES (42, "Mort Dinner Rick Andre", "June 20, 2021", "S05E01");
INSERT INTO episode VALUES (43, "Mortyplicity", "June 27, 2021", "S05E02");
INSERT INTO episode VALUES (44, "A Rickconvenient Mort", "July 4, 2021", "S05E03");
INSERT INTO episode VALUES (45, "Rickdependence Spray", "July 11, 2021", "S05E04");
INSERT INTO episode VALUES (46, "Amortycan Grickfitti", "July 18, 2021", "S05E05");
INSERT INTO episode VALUES (47, "Rick & Morty's Thanksploitation Spectacular", "July 25, 2021", "S05E06");
INSERT INTO episode VALUES (48, "Gotron Jerrysis Rickvangelion", "August 1, 2021", "S05E07");
INSERT INTO episode VALUES (49, "Rickternal Friendshine of the Spotless Mort", "August 8, 2021", "S05E08");
INSERT INTO episode VALUES (50, "Forgetting Sarick Mortshall", "September 5, 2021", "S05E09");
INSERT INTO episode VALUES (51, "Rickmurai Jack", "September 5, 2021", "S05E10");

/* Data for characters */
